name: auto update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
  push:
    paths:
      - '.github/workflows/autoupdate.yml'

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: test

      - name: Update Dockerfile with latest releases
        run: |
          DOXYGEN_VERSION=$(curl -s https://api.github.com/repos/doxygen/doxygen/releases/latest | jq -r '.tag_name')
          AWESOME_VERSION=$(curl -s https://api.github.com/repos/jothepro/doxygen-awesome-css/releases/latest | jq -r '.tag_name')
          PLANTUML_VERSION=$(curl -s https://api.github.com/repos/plantuml/plantuml/releases/latest | jq -r '.tag_name')
          sed -i "s/ARG DOXYGEN_VERSION=.*/ARG DOXYGEN_VERSION=$DOXYGEN_VERSION/" ./doxygen/Dockerfile
          sed -i "s/ARG AWESOME_VERSION=.*/ARG AWESOME_VERSION=$AWESOME_VERSION/" ./doxygen/Dockerfile
          sed -i "s/ARG PLANTUML_VERSION=.*/ARG PLANTUML_VERSION=$PLANTUML_VERSION/" ./doxygen/Dockerfile

      - name: Commit to new branch
        id: condition
        run: |
          git diff
          branch="auto-$(git hash-object ./doxygen/Dockerfile | head -c 7))

          if git rev-parse --verify "$branch" > /dev/null 2>&1 && [ -n "$(git status -s)" ]; then
            echo "should_open_pr=$branch" >> $GITHUB_OUTPUT
            git config user.name "${{ secrets.GIT_USER_NAME}}"
            git config user.email "${{ secrets.GIT_USER_MAIL}}"
            git add ./doxygen/Dockerfile
            git commit -m "build: automatic update doxygen"
            git checkout -b $branch
            git push -u
          else
            echo "should_open_pr=false" >> $GITHUB_OUTPUT
            echo "Dockerfile is up to date."
          fi

      - name: Open Pull Request
        if: steps.condition.outputs.should_open_pr != 'false'
        run: |
          response=$(curl -s -X POST -H "Authorization: token ${{ secrets.GIT_USER_TOKEN }}" -d \
          "{
            \"title\": \"doxygen update [autocommit]\",
            \"body\": \"check latest updates\",
            \"head\": \"rodrigodornelles:${{ steps.condition.outputs.should_open_pr }}\",
            \"base\": \"test\"
          }" "https://api.github.com/repos/rodrigodornelles/docker-images/pulls")
          
          PR_URL=$(echo "$response" | jq -r .html_url)
          echo "Created Pull Request: $PR_URL"
