name: doxygen

on:
  push:
    paths:
      - 'doxygen/*'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: rodrigodornelles
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: doxygen
          push: true
          tags: rodrigodornelles/doxygen:latest
          platforms: >
            linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,
            linux/mips64le,linux/ppc64le,linux/s390x
