name: sampgdk

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'sampgdk/*'
      - '.github/workflows/sampgdk.yml'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: rodrigodornelles
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: sampgdk
          push: true
          tags: rodrigodornelles/sampgdk:latest
          platforms: >
            linux/386,linux/amd64
