name: ziglang

on:
  workflow_dispatch:
  push:
    paths:
      - 'ziglang/*'

jobs:
  old:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['0.5.0', '0.4.0', '0.3.0', '0.2.0']
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: rodrigodornelles
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ziglang
          push: true
          tags: rodrigodornelles/ziglang:${{ matrix.version }}
          platforms: linux/amd64
          build-args: ZIG_VERSION=${{ matrix.version }}
