name: ziglang

on:
  workflow_dispatch:
  push:
    paths:
      - 'ziglang/*'
      - '.github/workflows/ziglang.yml'

env:
  ZIG_LATEST: '0.10.1'

jobs:
  old:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['0.5.0', '0.4.0', '0.3.0', '0.2.0']
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: rodrigodornelles
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ziglang
          push: true
          tags: rodrigodornelles/ziglang:${{ matrix.version }}
          platforms: linux/amd64
          build-args: |
            ZIG_VERSION=${{ matrix.version }}

  new:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['0.10.1', '0.10.0', '0.9.1', '0.9.0', '0.8.1', '0.8.0', '0.7.1', '0.7.0', '0.6.0']
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: rodrigodornelles
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ziglang
          push: true
          tags: rodrigodornelles/ziglang:${{ matrix.version }}
          platforms: >
            linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,
            linux/riscv64,linux/ppc64le,linux/s390x
          build-args: |
            ZIG_VERSION=${{ matrix.version }}

  latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: rodrigodornelles
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ziglang
          push: true
          tags: rodrigodornelles/ziglang:latest
          platforms: >
            linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,
            linux/riscv64,linux/ppc64le,linux/s390x
          build-args: |
            ZIG_VERSION=${{ env.ZIG_LATEST }}
